# https://trakt.docs.apiary.io

https://api.trakt.tv
trakt-api-key: $TRAKT_CLIENT_ID
trakt-api-version: 2
Authorization: Bearer $TRAKT_ACCESS_TOKEN
--

--
POST /oauth/device/code
client_id: $TRAKT_CLIENT_ID

--
POST /oauth/device/token
code: $TRAK_DEVICE_CODE
client_id: $TRAKT_CLIENT_ID
client_secret: $TRAKT_CLIENT_SECRET

--
GET /users/me/watchlist/movies/added
