name: Github Pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - shell: bash
        env:
          TRAKT_CLIENT_ID: ${{secrets.TRAKT_CLIENT_ID}}
          TRAKT_CLIENT_SECRET: ${{secrets.TRAKT_CLIENT_SECRET}}
          TRAKT_ACCESS_TOKEN: ${{secrets.TRAKT_ACCESS_TOKEN}}
          TMDB_ACCESS_TOKEN: ${{secrets.TMDB_ACCESS_TOKEN}}
        run: bundle exec bin/lebowski providers > site/data.json

      - shell: bash
        run: bundle exec bin/lebowski diff > site/diff.json

      - shell: bash
        run: bundle exec bin/lebowski updates > site/updates.json

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
